RAW_SPARK_DATA_PATH = 'data/raw/2024_sample/'
RAW_DATA_PATH = 'data/raw/'
EXTENDS_DATA_PATH = 'data/extends/'
PROCESSED_DATA_PATH = 'data/processed/'
OBJECTS_PATH = 'src/objects/'
LOGS_PATH = 'logs/'
MODELS_PATH = 'src/models/save_models/'