RAW_SPARK_DATA_PATH = 'data/raw/2024_sample/'
RAW_DATA_PATH = 'data/raw/'
EXTENDS_DATA_PATH = 'data/extends/'
PREPROCESSED_DATA_PATH = 'data/preprocessed/'
OBJECTS_PATH = 'src/objects/'
LOGS_PATH = 'logs/'
SAVE_MODELS_PATH = 'src/models/save_models/'
MODELS_PATH = 'src/models/'